/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/dec23test.glb
*/

import { useAnimations, useGLTF } from "@react-three/drei";
import React, { useEffect, useRef } from "react";

export function Character({ animation, ...props }) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/models/dec27test1-transformed.glb");
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    actions[animation]?.reset().fadeIn(0.24).play();
    return () => actions?.[animation]?.fadeOut(0.24);
  }, [animation]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="root_ctrl" rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <group name="R_kneel_ctrl" rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <group name="L_foot_ctrl" rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <group name="L_kneel_ctrl" rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <group name="R_foot_ctrl" rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <group name="monkeidle" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <skinnedMesh
            name="chimp_geo"
            geometry={nodes.chimp_geo.geometry}
            material={materials._a_c_chimp_1a_c_chimp_1_1}
            skeleton={nodes.chimp_geo.skeleton}
            castShadow
            receiveShadow
          />
          <primitive object={nodes.COG_J} />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/dec27test1-transformed.glb");