/*
  CrabEnemy.jsx
  Auto-generated by: https://github.com/pmndrs/gltfjsx
  Command: npx gltfjsx models/crabenemy.glb
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'


export function CrabEnemy({ animation = "MonsterArmature|Idle", ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/crabenemy.glb')
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    // Fade into whichever animation is set:
    if (actions[animation]) {
      actions[animation].reset().fadeIn(0.25).play()
    }

    // On unmount or on animation change, fade out old animation
    return () => {
      if (actions[animation]) {
        actions[animation].fadeOut(0.25)
      }
    }
  }, [animation, actions])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Root_Scene">
        <group name="RootNode">
          <group
            name="MonsterArmature"
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <primitive object={nodes.Body} />
            <primitive object={nodes.Head} />
          </group>
          <group name="Crab" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <skinnedMesh
              name="Crab_1"
              geometry={nodes.Crab_1.geometry}
              material={materials.Main}
              skeleton={nodes.Crab_1.skeleton}
            />
            <skinnedMesh
              name="Crab_2"
              geometry={nodes.Crab_2.geometry}
              material={materials.Black}
              skeleton={nodes.Crab_2.skeleton}
            />
            <skinnedMesh
              name="Crab_3"
              geometry={nodes.Crab_3.geometry}
              material={materials.Main_Dark}
              skeleton={nodes.Crab_3.skeleton}
            />
            <skinnedMesh
              name="Crab_4"
              geometry={nodes.Crab_4.geometry}
              material={materials.White}
              skeleton={nodes.Crab_4.skeleton}
            />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/crabenemy.glb')
